In [20]:
from tensorflow.keras.preprocessing.text import one_hot

In [21]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [22]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [23]:
## Define the vocabulary size
voc_size=10000

In [24]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [25]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1605, 9243, 2266, 9999],
 [1605, 9243, 2266, 9295],
 [1605, 3859, 2266, 3381],
 [6924, 1279, 727, 7712, 8703],
 [6924, 1279, 727, 7712, 8586],
 [1257, 1605, 8152, 2266, 2074],
 [5732, 500, 1294, 7712]]

In [26]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [27]:
import numpy as np

In [28]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1605 9243 2266 9999]
 [   0    0    0    0 1605 9243 2266 9295]
 [   0    0    0    0 1605 3859 2266 3381]
 [   0    0    0 6924 1279  727 7712 8703]
 [   0    0    0 6924 1279  727 7712 8586]
 [   0    0    0 1257 1605 8152 2266 2074]
 [   0    0    0    0 5732  500 1294 7712]]


In [29]:
## feature representation
dim=10

In [30]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [31]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step


array([[[ 0.04842892, -0.0073682 , -0.00573687,  0.02667092,
          0.01584635, -0.00074013, -0.01038879,  0.00591458,
          0.02632548, -0.01635461],
        [ 0.04842892, -0.0073682 , -0.00573687,  0.02667092,
          0.01584635, -0.00074013, -0.01038879,  0.00591458,
          0.02632548, -0.01635461],
        [ 0.04842892, -0.0073682 , -0.00573687,  0.02667092,
          0.01584635, -0.00074013, -0.01038879,  0.00591458,
          0.02632548, -0.01635461],
        [ 0.04842892, -0.0073682 , -0.00573687,  0.02667092,
          0.01584635, -0.00074013, -0.01038879,  0.00591458,
          0.02632548, -0.01635461],
        [ 0.01568503,  0.01783017, -0.01942536, -0.03284711,
          0.04478789, -0.00518758, -0.03998818, -0.01056356,
         -0.00041622,  0.0132401 ],
        [-0.0175476 ,  0.0107043 , -0.02355936,  0.04904032,
         -0.01868743,  0.03364294,  0.03042128,  0.01785364,
          0.01335612, -0.00144073],
        [ 0.00374775,  0.00834782,  0.03412321, -0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 1605, 9243, 2266, 9999])

In [19]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step


array([[-0.01811117,  0.03878126, -0.02737235, -0.01839937,  0.03398464,
         0.04589481,  0.0050789 , -0.02054358,  0.04402491, -0.00597354],
       [-0.01811117,  0.03878126, -0.02737235, -0.01839937,  0.03398464,
         0.04589481,  0.0050789 , -0.02054358,  0.04402491, -0.00597354],
       [-0.01811117,  0.03878126, -0.02737235, -0.01839937,  0.03398464,
         0.04589481,  0.0050789 , -0.02054358,  0.04402491, -0.00597354],
       [-0.01811117,  0.03878126, -0.02737235, -0.01839937,  0.03398464,
         0.04589481,  0.0050789 , -0.02054358,  0.04402491, -0.00597354],
       [-0.03740193,  0.04880038,  0.01851625, -0.04799849,  0.01885613,
        -0.00195587,  0.04367472, -0.02252017, -0.03603203,  0.03788909],
       [-0.02944459,  0.00018636, -0.02103593,  0.01307564, -0.04735508,
        -0.04447651, -0.00616105,  0.00661284,  0.01814907, -0.03979412],
       [-0.02687751,  0.0382551 ,  0.0494766 ,  0.02931112,  0.0082728 ,
        -0.03545471, -0.03391651, -0.00409236